"""Add OCR fields to Document

Revision ID: 61b78b41809f
Revises: e59e098913e2
Create Date: 2026-09-12 10:58:12.437750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61b78b41809f'
down_revision: Union[str, None] = 'e59e098913e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('ocr_status', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('extracted_name', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('extracted_document_number', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('extracted_date_of_birth', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('extracted_expiry_date', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('extracted_address', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'extracted_address')
    op.drop_column('documents', 'extracted_expiry_date')
    op.drop_column('documents', 'extracted_date_of_birth')
    op.drop_column('documents', 'extracted_document_number')
    op.drop_column('documents', 'extracted_name')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'verification_status')
    op.drop_column('documents', 'ocr_status')
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
